*** Starting uWSGI 2.0.19.1 (64bit) on [Wed Oct 28 11:14:07 2020] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-28) on 23 October 2020 05:56:17
os: Linux-3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018
nodename: bko-ace2updap04.internal.chinacloudapp.cn
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /app/git/sephora_search/Sephora_cn_Personalization_II
writing pidfile to uwsgi.pid
detected binary path: /app/git/sephora_search/Sephora_cn_Personalization_II/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /app/git/sephora_search/Sephora_cn_Personalization_II
your processes number limit is 64026
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8888 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:38236 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Jan 22 2020, 17:24:30)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
PEP 405 virtualenv detected: /app/git/sephora_search/Sephora_cn_Personalization_II/venv
Set PythonHome to /app/git/sephora_search/Sephora_cn_Personalization_II/venv
Python main interpreter initialized at 0x2408450
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 6648384 bytes (6492 KB) for 500 cores
*** Operational MODE: preforking+threaded ***
/app/git/sephora_search/Sephora_cn_Personalization_II/venv/lib/python3.6/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.993 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "./wsgi.py", line 1, in <module>
    from web_app.app import app as application
  File "./web_app/app.py", line 20, in <module>
    from web_app.service_suggest import SuggestService
  File "./web_app/service_suggest.py", line 15, in <module>
    from lib.processing.keyword_tag_mapping import get_extended_kw2tag, get_fixed_kw2tag
  File "./lib/processing/keyword_tag_mapping.py", line 6, in <module>
    from lib.datastructure.files import STANDARD_TAG2KW, STANDARD_KW2TAG, EXTENDED_KW2TAG, EXTENDED_TAG2KW, KW2TAG_FIXED, \
ImportError: cannot import name 'TRANSLATION'
unable to load app 0 (mountpoint='') (callable not found or import error)
failed to open python file Sephora_cn_Personalization_II/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 54872)
spawned uWSGI worker 1 (pid: 54885, cores: 100)
spawned uWSGI worker 2 (pid: 54891, cores: 100)
spawned uWSGI worker 3 (pid: 54920, cores: 100)
spawned uWSGI worker 4 (pid: 55005, cores: 100)
spawned uWSGI worker 5 (pid: 55128, cores: 100)
spawned uWSGI http 1 (pid: 55203)
